// linkdrop
mod create_user;
mod create_user_name_is_already_exists;
mod create_user_not_enough_balance;
mod create_user_with_low_gas;
// user
mod create_near_campaign;
mod create_near_campaign_incorrect_name;
// near-campaign
mod add_existing_keys;
mod add_keys_clear_and_delete_campaign;
mod add_multiple_keys;
mod add_one_key;
mod claim_non_existing_account;
mod claim_one_link;
mod clear_multiple_keys;
mod clear_non_existing_keys;
mod create_account_and_claim_that_already_exists;
mod create_one_account_and_claim;
mod delete_campaign_with_active_keys;
mod refund_inactive_or_non_existing_keys;
mod refund_multiple_keys;
mod refund_non_existing_account;
mod dev_test;

mod utils;
